#version: "3"
services:
  mysql:
    image: "mysql:8.0.41"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user
  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - 6379:6379